#!/usr/bin/env sh
IS_CARGO="test -e Cargo.toml"

if [ ! -d .git ]; then
    echo "not git controlled"
    exit 0
fi

_version() {
    curr=v$(date +%g.%m.)
    tag=$(git describe --tags --abbrev=0)
    minor=00
    if echo "$tag" | grep -q "$curr*"; then
        minor=$(echo "$tag" | cut -d '.' -f 3 | sed 's/^0//g')
        minor=$((minor+1))
        if [ $minor -lt 10 ]; then
            minor="0$minor"
        fi
    fi
    vers="$curr$minor"
    if $IS_CARGO; then
        vers=$(echo "$vers" | sed 's/^v//g;s/\.0/./g')
        sed -i 's/^version =.*/version = "'"$vers"'"/' Cargo.toml
    else
        echo "$vers"
    fi
}

_main() {
    if $IS_CARGO; then
        _version
    else
        _version > cmd/vers.txt
    fi
}

_main
