language = ""
platform = ""
readonly = false
store = ""
include = []
interactive = true

[defaults]
modtime = ""
completion = ""

[color]
enabled = true

[clip]
copy_command = []
paste_command = []
timeout = 0
osc52 = false
enabled = true

[hooks]
enabled = true
directory = ""

[json]
mode = ""
hash_length = 0

[credentials]
key_file = ""
password_mode = ""
password = []

[pwgen]
enabled = true
characters = ""
word_count = 0
template = ""
title = true
words_command = []

[totp]
enabled = true
entry = ""
color_windows = []
otp_format = ""
timeout = 0
